import type { Metadata } from "next";
import { Mulish, DM_Sans } from 'next/font/google';
import "./globals.css";


const mulish = Mulish({
  subsets: ['latin'],
  display: 'swap',
  // You can add variable less names for use in CSS if needed:
  // variable: '--font-mulish',
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap"
})


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.className} ${dmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
